FROM kalilinux/kali-rolling
LABEL org.opencontainers.image.authors="githubfoam"


#clean start
RUN apt-get update -y && apt-get upgrade -y && apt-get autoremove - && apt-get clean 

RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections && \
    apt-get install -y kali-tools-reverse-engineering && \
    echo "########################### METAPACKAGE INFO ###########################" && \
    apt depends kali-tools-reverse-engineering  && \
    apt show kali-tools-reverse-engineering && \
    apt-cache show kali-tools-reverse-engineering | grep Depends && \
    echo "########################### METAPACKAGE INFO ###########################"


# custom packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    aircrack-ng \
    ncat  \
    hping3

#testing
RUN hping3 -v

