name: "ZAP - API"


on:
  push:
    branches: [ test ]
  schedule:
      - cron:  '0 0 1 * *' ##execution of a task in the first minute of the month 


jobs:

# https://www.zaproxy.org/docs/docker/api-scan/
 ubuntu-latest-zap-API-job:
    name: "ZAP - API Scan"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status  
    - name: "ZAP - API Scan"
      run: | 
        # https://www.zaproxy.org/blog/2017-06-19-scanning-apis-with-zap/
        docker run -t owasp/zap2docker-weekly zap-api-scan.py -t \  
          https://www.example.com/openapi.json -f openapi 

 ubuntu-latest-zap-API-props-job:
    name: "ZAP - API Scan props"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status  
    - name: "ZAP - API Scan props"
      run: | 
        # https://www.zaproxy.org/blog/2017-06-19-scanning-apis-with-zap/
        docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-weekly zap-api-scan.py \  
        -t https://www.example.com/openapi.json -f openapi \  
        -z "-configfile /zap/wrk/options.prop" 