name: "cyberrange CI workflow"

on:
  push:
    branches: [ test]

jobs:

  ubuntu-latest-job:
    name: "build cyberrange ubuntu latest"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: |
        hostnamectl status
        lsb_release -a
        lsb_release -d
        cat /etc/lsb-release
        cat /etc/issue
        cat /etc/os-release
        sudo apt-get install -y neofetch && neofetch   
    - name: "docker build kali linux compose"
      run: |
        sudo mkdir /mnt/share-kali
        sudo docker-compose --file dockerfiles/kalilinux/kali.yml up -d
        sudo docker-compose --file dockerfiles/kalilinux/kali.yml ps
        docker network ls
        docker exec kali /bin/bash sh -c "nmap -O -A -sV 192.168.35.5"
